# This file is a template, and might need editing before it works on your project.
# This file is a template demonstrating the `script` keyword.
# Learn more about this keyword here: https://docs.gitlab.com/ee/ci/yaml/README.html#script

# After committing this template, visit CI/CD > Jobs to see the script output.
default:
  image: node:latest

run-npm:
  script:
    - npm i
    - printf 'CCS_MOBILE = "5511961834601@c.us"\nCCS_CDN_FILE = "https://cdn-homolog.ubicuacloud.com.com/file/"\nCCS_CDN_BASE = "https://cdn-homolog.ubicuacloud.com.com/base64/"\nCCS_OPTIONSKEY = "/etc/letsencrypt/live/ccs-homolog.ubicuacloud.com.br/privkey.pem"\nCCS_OPTIONSCERT = "/etc/letsencrypt/live/ccs-homolog.ubicuacloud.com.br/fullchain.pem"\nCCS_EXTENSION = "https://extensao-homolog.ubicuacloud.com.br/client"\nCCS_REPORT = "https://ccs-homolog.ubicuacloud.com.br/supervisor/report/"\nSMI_API = "https://cruzeirodosul.ex-aluno-edu.com.br/cruzeiro_m7/api/wsfMsg"\nDB_HOST = "localhost"\nDB_USER = "admin"\nDB_PASSWORD = "GmtB0kCs*Fic"\nDB_DATABASE = "db_cruzeiro_ccs"' > .env
    - forever stopall
    - forever start app.js
    - forever -c python3 sentinel.py 

# create-env:
#   script:
#     - printf 'CCS_MOBILE = "5511961834601@c.us"\nCCS_CDN_FILE = "https://cdn-homolog.ubicuacloud.com.com/file/"\nCCS_CDN_BASE = "https://cdn-homolog.ubicuacloud.com.com/base64/"\nCCS_OPTIONSKEY = "/etc/letsencrypt/live/ccs-homolog.ubicuacloud.com.br/privkey.pem"\nCCS_OPTIONSCERT = "/etc/letsencrypt/live/ccs-homolog.ubicuacloud.com.br/fullchain.pem"\nCCS_EXTENSION = "https://extensao-homolog.ubicuacloud.com.br/client"\nCCS_REPORT = "https://ccs-homolog.ubicuacloud.com.br/supervisor/report/"\nSMI_API = "https://cruzeirodosul.ex-aluno-edu.com.br/cruzeiro_m7/api/wsfMsg"\nDB_HOST = "localhost"\nDB_USER = "admin"\nDB_PASSWORD = "GmtB0kCs*Fic"\nDB_DATABASE = "db_cruzeiro_ccs"' > .env

# start-node:
#   script:
#     - node app.js