# This file is a template, and might need editing before it works on your project.
# This file is a template demonstrating the `script` keyword.
# Learn more about this keyword here: https://docs.gitlab.com/ee/ci/yaml/README.html#script

# After committing this template, visit CI/CD > Jobs to see the script output.
default:
  image: node:latest

# run-npm:
#   script:
#     - npm i
#     - echo 'Teste'

create-env:
  script:
    -> printf 
    'CCS_MOBILE = "5511961834601@c.us"
    CCS_CDN_FILE = "https://cdn-homolog.ubicuacloud.com.com/file/"
    CCS_CDN_BASE = "https://cdn-homolog.ubicuacloud.com.com/base64/"
    CCS_OPTIONSKEY = "/etc/letsencrypt/live/ccs-homolog.ubicuacloud.com.br/privkey.pem"
    CCS_OPTIONSCERT = "/etc/letsencrypt/live/ccs-homolog.ubicuacloud.com.br/fullchain.pem"
    CCS_EXTENSION = "https://extensao-homolog.ubicuacloud.com.br/client"
    CCS_REPORT = "https://ccs-homolog.ubicuacloud.com.br/supervisor/report/"
    SMI_API = "https://cruzeirodosul.ex-aluno-edu.com.br/cruzeiro_m7/api/wsfMsg"
    DB_HOST = "localhost"
    DB_USER = "admin"
    DB_PASSWORD = "GmtB0kCs*Fic"
    DB_DATABASE = "db_cruzeiro_ccs"' > .env

# start-node:
#   script:
#     - node app.js
#     - echo 'Foi'